export const tvShowsType = {
  FETCH_TVSHOWS_REQUEST: "FETCH_TVSHOWS_REQUEST",
  FETCH_TVSHOWS_SUCCESS: "FETCH_TVSHOWS_SUCCESS",
  FETCH_TVSHOWS_FAILURE: "FETCH_TVSHOWS_FAILURE",

  RESET_TVSHOWS_LIST: "RESET_TVSHOWS_LIST",

  FETCH_TVSHOW_DETAILS_REQUEST: "FETCH_TVSHOW_DETAILS_REQUEST",
  FETCH_TVSHOW_DETAILS_SUCCESS: "FETCH_TVSHOW_DETAILS_SUCCESS",
  FETCH_TVSHOW_DETAILS_FAILURE: "FETCH_TVSHOW_DETAILS_FAILURE",

  RESET_TVSHOW_DETAILS: "RESET_TVSHOW_DETAILS",

  FETCH_TVEPISODES_REQUEST: "FETCH_TVEPISODES_REQUEST",
  FETCH_TVEPISODES_SUCCESS: "FETCH_TVEPISODES_SUCCESS",
  FETCH_TVEPISODES_FAILURE: "FETCH_TVEPISODES_FAILURE",

  FETCH_TVSHOW_CAST_REQUEST: "FETCH_TVSHOW_CAST_REQUEST",
  FETCH_TVSHOW_CAST_SUCCESS: "FETCH_TVSHOW_CAST_SUCCESS",
  FETCH_TVSHOW_CAST_FAILURE: "FETCH_TVSHOW_CAST_FAILURE",

  FETCH_TVSHOW_RATING_REQUEST: "FETCH_TVSHOW_RATING_REQUEST",
  FETCH_TVSHOW_RATING_SUCCESS: "FETCH_TVSHOW_RATING_SUCCESS",
  FETCH_TVSHOW_RAITING_FAILURE: "FETCH_TVSHOW_RAITING_FAILURE",
};
